"""Add parent_id to MenuItem

Revision ID: 8b60d7d44bb8
Revises: d6d26a7af164
Create Date: 2026-07-14 03:41:54.054595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8b60d7d44bb8'
down_revision: Union[str, Sequence[str], None] = 'd6d26a7af164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
